'use client'

export const dynamic = 'force-dynamic'

import { useEffect, useState, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase'
import WaveDivider from '@/app/components/WaveDivider'

type TestResult = {
  health_score: number
  created_at: string
  ph: number | null
  free_chlorine: number | null
  total_alkalinity: number | null
  cya: number | null
  calcium_hardness: number | null
  salt: number | null
  recommendations: {
    action: { param: string; title: string; desc: string; tags: string[] }[]
    monitor: { param: string; title: string; desc: string; tags: string[] }[]
    good: { param?: string; title: string; desc: string }[]
    unknown: { param: string; title: string; desc: string; tags: string[] }[]
  }
}

// Compute score from recommendations so the share page always matches the dashboard,
// regardless of what health_score value was stored in the database.
function computeScore(recs: TestResult['recommendations']): number {
  const actionCount = recs.action.length
  const monitorCount = recs.monitor.length
  const unknownCount = recs.unknown.filter(u => u.param !== 'salt').length
  return Math.max(10, 100 - actionCount * 18 - monitorCount * 6 - unknownCount * 8)
}

const READINGS = [
  { key: 'ph',               label: 'pH',                    fmt: (v: number) => v.toFixed(1),  ideal: '7.2 – 7.6' },
  { key: 'free_chlorine',    label: 'Free Chlorine',         fmt: (v: number) => `${v} ppm`,    ideal: '1 – 3 ppm' },
  { key: 'total_alkalinity', label: 'Total Alkalinity',      fmt: (v: number) => `${v} ppm`,    ideal: '80 – 120 ppm' },
  { key: 'cya',              label: 'Cyanuric Acid (CYA)',   fmt: (v: number) => `${v} ppm`,    ideal: '30 – 50 ppm' },
  { key: 'calcium_hardness', label: 'Calcium Hardness',      fmt: (v: number) => `${v} ppm`,    ideal: '200 – 400 ppm' },
  { key: 'salt',             label: 'Salt',                  fmt: (v: number) => `${v} ppm`,    ideal: '2700 – 3400 ppm' },
]

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
}

function scoreLabel(score: number) {
  if (score >= 90) return 'Excellent condition'
  if (score >= 75) return 'Good condition'
  if (score >= 55) return 'Needs attention'
  return 'Action required'
}

function buildReportText(poolName: string, test: TestResult): string {
  const score = computeScore(test.recommendations)
  const lines: string[] = []
  lines.push(`POOL REPORT — ${poolName}`)
  lines.push(`Tested: ${formatDate(test.created_at)}`)
  lines.push(`Health Score: ${score}/100 (${scoreLabel(score)})`)
  lines.push('')
  lines.push('READINGS')
  READINGS.forEach(p => {
    const val = test[p.key as keyof TestResult]
    if (typeof val === 'number') {
      lines.push(`  ${p.label}: ${p.fmt(val)}  (Ideal: ${p.ideal})`)
    } else {
      lines.push(`  ${p.label}: Not tested`)
    }
  })
  if (test.recommendations.action.length > 0) {
    lines.push('')
    lines.push('ACTION NEEDED')
    test.recommendations.action.forEach(r => {
      lines.push(`  • ${r.title}`)
      lines.push(`    ${r.desc}`)
      if (r.tags.length > 0) lines.push(`    ${r.tags.join(' · ')}`)
    })
  }
  if (test.recommendations.monitor.length > 0) {
    lines.push('')
    lines.push('KEEP AN EYE ON')
    test.recommendations.monitor.forEach(r => {
      lines.push(`  • ${r.title}`)
      lines.push(`    ${r.desc}`)
    })
  }
  if (test.recommendations.good.length > 0) {
    lines.push('')
    lines.push('LOOKING GOOD')
    test.recommendations.good.forEach(r => {
      lines.push(`  ✓ ${r.title}`)
    })
  }
  lines.push('')
  lines.push('Generated by PoolKeep')
  return lines.join('\n')
}

function buildSmsText(poolName: string, test: TestResult): string {
  const score = computeScore(test.recommendations)
  const parts = [`${poolName} pool report (score ${score}/100 — ${scoreLabel(score)})`]
  if (test.recommendations.action.length > 0) {
    parts.push(`Action needed: ${test.recommendations.action.map(r => r.title).join(', ')}`)
  } else {
    parts.push('All clear — no action needed')
  }
  const readings = READINGS
    .filter(p => test[p.key as keyof TestResult] !== null)
    .map(p => `${p.label} ${(p.fmt as (v: number) => string)(test[p.key as keyof TestResult] as number)}`)
    .join(', ')
  if (readings) parts.push(`Readings: ${readings}`)
  parts.push('Sent from PoolKeep')
  return parts.join('\n')
}

export default function SharePage() {
  const router = useRouter()
  const [test, setTest] = useState<TestResult | null>(null)
  const [pool, setPool] = useState<{ name: string } | null>(null)
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)
  const printRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const supabase = createClient()
    supabase.auth.getUser().then(async ({ data }) => {
      if (!data.user) { router.push('/login'); return }
      const { data: pools } = await supabase.from('pools').select('id,name').order('created_at', { ascending: true })
      if (!pools || pools.length === 0) { router.push('/setup/pool'); return }
      // Use the same active pool the dashboard uses
      const savedId = typeof window !== 'undefined' ? localStorage.getItem('poolkeep_active_pool') : null
      const activePool = (savedId && pools.find(p => p.id === savedId)) || pools[0]
      setPool(activePool)
      const { data: tests } = await supabase
        .from('test_results')
        .select('health_score,recommendations,created_at,ph,free_chlorine,total_alkalinity,cya,calcium_hardness,salt')
        .eq('pool_id', activePool.id)
        .order('created_at', { ascending: false })
        .limit(1)
      if (tests && tests.length > 0) setTest(tests[0])
      setLoading(false)
    })
  }, [router])

  function handleEmail() {
    if (!test || !pool) return
    const subject = encodeURIComponent(`Pool Report — ${pool.name} — ${formatDate(test.created_at)}`)
    const body = encodeURIComponent(buildReportText(pool.name, test))
    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  function handleSms() {
    if (!test || !pool) return
    const body = encodeURIComponent(buildSmsText(pool.name, test))
    window.open(`sms:?body=${body}`)
  }

  async function handleNativeShare() {
    if (!test || !pool) return
    const text = buildReportText(pool.name, test)
    if (navigator.share) {
      await navigator.share({
        title: `Pool Report — ${pool.name}`,
        text,
      })
    }
  }

  async function handleCopy() {
    if (!test || !pool) return
    await navigator.clipboard.writeText(buildReportText(pool.name, test))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handlePrint() {
    window.print()
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-surface flex flex-col" style={{maxWidth:480,margin:'0 auto'}}>
        <div className="bg-pool-deep px-5 pt-5 pb-8 animate-pulse">
          <div className="flex items-center gap-3 mb-6">
            <div className="h-5 w-5 rounded bg-white/15" />
            <div className="h-4 w-20 rounded-full bg-white/15" />
          </div>
          <div className="h-3 w-16 rounded-full bg-white/15 mb-2" />
          <div className="h-7 w-40 rounded-full bg-white/20 mb-1" />
          <div className="h-3 w-28 rounded-full bg-white/15 mt-1" />
          <div className="flex flex-col items-center mt-6 gap-3">
            <div className="w-24 h-24 rounded-full bg-white/10" />
            <div className="h-4 w-28 rounded-full bg-white/15" />
          </div>
        </div>
        <WaveDivider />
        <div className="flex-1 px-4 pt-4 pb-10 animate-pulse space-y-3">
          <div className="h-12 rounded-2xl bg-white shadow-sm" />
          {[1,2,3,4,5].map(i => <div key={i} className="h-10 rounded-xl bg-white shadow-sm" />)}
        </div>
      </div>
    )
  }

  const canNativeShare = typeof navigator !== 'undefined' && !!navigator.share
  const isMobile = typeof navigator !== 'undefined' && /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent)

  return (
    <>
      {/* Print styles — only applied when printing */}
      <style>{`
        @media print {
          .no-print { display: none !important; }
          .print-only { display: block !important; }
          body { background: white; }
          .print-report { box-shadow: none !important; border: none !important; }
        }
        .print-only { display: none; }
      `}</style>

      <div className="min-h-screen bg-surface flex flex-col" style={{maxWidth:480,margin:'0 auto'}}>

        {/* Header */}
        <div className="bg-pool-deep px-5 pt-5 pb-6 no-print">
          <div className="flex items-center gap-3 mb-6">
            <button onClick={() => router.push('/dashboard')} className="text-white/60 hover:text-white transition-colors">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
            </button>
            <span className="text-white text-base" style={{fontFamily:"'Space Grotesk',sans-serif",fontWeight:300}}>
              Pool<span style={{fontWeight:800}}>Keep</span>
            </span>
          </div>
          <p className="text-white/50 text-xs font-semibold uppercase tracking-widest mb-1">{pool?.name ?? 'My Pool'}</p>
          <h1 className="text-white text-2xl font-bold" style={{fontFamily:"'Oswald',sans-serif",letterSpacing:'-.01em'}}>Share Report</h1>
          <p className="text-white/55 text-sm mt-1">Send to yourself, your pool store, or someone else</p>
        </div>

        {/* Wave */}
        <WaveDivider className="no-print" />

        <div className="flex-1 px-4 pt-4 pb-28 bg-surface">
          {!test ? (
            <div className="bg-white rounded-2xl p-6 shadow-sm text-center">
              <p className="text-text-primary font-semibold mb-1">No test results yet</p>
              <p className="text-text-muted text-sm mb-4">Log a water test first to generate a shareable report.</p>
              <button onClick={() => router.push('/log')} className="bg-pool-dark text-white text-sm font-bold px-5 py-2.5 rounded-xl hover:opacity-90 transition-opacity">
                Log a Test →
              </button>
            </div>
          ) : (
            <>
              {/* Printable report */}
              <div ref={printRef} className="print-report bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden mb-5">

                {/* Report header */}
                <div className="px-5 py-4 border-b border-gray-100" style={{background:'#F8FBFD'}}>
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-[10px] font-bold uppercase tracking-widest text-text-muted mb-0.5">Pool Report</p>
                      <p className="font-bold text-text-primary text-base">{pool?.name}</p>
                      <p className="text-text-muted text-xs mt-0.5">{formatDate(test.created_at)}</p>
                    </div>
                    {(() => {
                      const score = computeScore(test.recommendations)
                      const unknownNonSalt = test.recommendations.unknown.filter(u => u.param !== 'salt').length
                      return (
                        <div className="text-right shrink-0">
                          <p className="text-3xl font-bold leading-none" style={{fontFamily:"'Oswald',sans-serif",color:'#0078B8'}}>{score}</p>
                          <p className="text-[10px] font-semibold uppercase tracking-wide mt-0.5" style={{color:'#0078B8'}}>/ 100</p>
                          <p className="text-[11px] text-text-muted mt-0.5">{scoreLabel(score)}</p>
                          {unknownNonSalt > 0 && (
                            <p className="text-[10px] text-text-faint mt-0.5">Based on {5 - unknownNonSalt} of 5</p>
                          )}
                        </div>
                      )
                    })()}
                  </div>
                </div>

                {/* Readings table */}
                <div className="px-5 py-4 border-b border-gray-100">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-text-muted mb-3">Readings</p>
                  <div className="space-y-2">
                    {READINGS.map(p => {
                      const val = test[p.key as keyof TestResult]
                      const hasVal = typeof val === 'number'
                      const isAction = test.recommendations.action.some(r => r.title.toLowerCase().includes(p.label.split(' ')[0].toLowerCase()))
                      const isMonitor = !isAction && test.recommendations.monitor.some(r => r.title.toLowerCase().includes(p.label.split(' ')[0].toLowerCase()))
                      const isGood = !isAction && !isMonitor && hasVal
                      const statusColor = !hasVal ? '#C5D8E4' : isAction ? '#E5304A' : isMonitor ? '#F5A623' : '#1DB869'
                      const statusLabel = !hasVal ? 'Not tested' : isAction ? 'Action needed' : isMonitor ? 'Monitor' : 'Good'
                      return (
                        <div key={p.key} className="flex items-center justify-between">
                          <span className="text-xs text-text-muted">{p.label}</span>
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-bold" style={{fontFamily:"'DM Mono',monospace", color: hasVal ? '#1A2E3B' : '#C5D8E4'}}>
                              {hasVal ? p.fmt(val as number) : '—'}
                            </span>
                            <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full" style={{background: `${statusColor}18`, color: statusColor}}>
                              {statusLabel}
                            </span>
                          </div>
                        </div>
                      )
                    })}
                  </div>
                </div>

                {/* Action items */}
                {test.recommendations.action.length > 0 && (
                  <div className="px-5 py-4 border-b border-gray-100">
                    <p className="text-[10px] font-bold uppercase tracking-widest mb-2" style={{color:'#E5304A'}}>Action Needed</p>
                    <div className="space-y-2">
                      {test.recommendations.action.map((r, i) => (
                        <div key={i}>
                          <p className="text-xs font-bold text-text-primary">{r.title}</p>
                          <p className="text-[11px] text-text-muted leading-relaxed">{r.desc}</p>
                          {r.tags.length > 0 && <p className="text-[10px] mt-1" style={{color:'#0078B8'}}>{r.tags.join(' · ')}</p>}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Monitor items */}
                {test.recommendations.monitor.length > 0 && (
                  <div className="px-5 py-4 border-b border-gray-100">
                    <p className="text-[10px] font-bold uppercase tracking-widest mb-2" style={{color:'#D48800'}}>Keep an Eye On</p>
                    <div className="space-y-2">
                      {test.recommendations.monitor.map((r, i) => (
                        <div key={i}>
                          <p className="text-xs font-bold text-text-primary">{r.title}</p>
                          <p className="text-[11px] text-text-muted leading-relaxed">{r.desc}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Good items */}
                {test.recommendations.good.length > 0 && (
                  <div className="px-5 py-4">
                    <p className="text-[10px] font-bold uppercase tracking-widest mb-2" style={{color:'#1DB869'}}>Looking Good</p>
                    <div className="flex flex-wrap gap-x-4 gap-y-1">
                      {test.recommendations.good.map((r, i) => (
                        <div key={i} className="flex items-center gap-1.5">
                          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#1DB869" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
                          <span className="text-[11px] font-medium text-text-primary">{r.title}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Footer */}
                <div className="px-5 py-3 border-t border-gray-100" style={{background:'#F8FBFD'}}>
                  <p className="text-[10px] text-text-faint text-center">Generated by PoolKeep · poolkeep.app</p>
                </div>
              </div>

              {/* Share buttons */}
              <div className="no-print space-y-3 mb-6">
                <p className="text-xs font-bold uppercase tracking-widest text-text-muted mb-3">Share via</p>

                {canNativeShare && (
                  <button onClick={handleNativeShare} className="w-full bg-white rounded-2xl px-4 py-3.5 shadow-sm border border-gray-100 flex items-center gap-3 text-left hover:border-pool-dark transition-colors">
                    <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:'rgba(0,120,184,0.08)'}}>
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0078B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>
                    </div>
                    <div>
                      <p className="text-sm font-bold text-text-primary">Share</p>
                      <p className="text-xs text-text-muted">Message, AirDrop, social, and more</p>
                    </div>
                  </button>
                )}

                <button onClick={handleEmail} className="w-full bg-white rounded-2xl px-4 py-3.5 shadow-sm border border-gray-100 flex items-center gap-3 text-left hover:border-pool-dark transition-colors">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:'rgba(0,120,184,0.08)'}}>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0078B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
                  </div>
                  <div>
                    <p className="text-sm font-bold text-text-primary">Email</p>
                    <p className="text-xs text-text-muted">Send full report to yourself or your pool store</p>
                  </div>
                </button>

                <button onClick={isMobile ? handleSms : undefined} disabled={!isMobile} className="w-full bg-white rounded-2xl px-4 py-3.5 shadow-sm border border-gray-100 flex items-center gap-3 text-left transition-colors" style={{opacity: isMobile ? 1 : 0.5, cursor: isMobile ? 'pointer' : 'default'}}>
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:'rgba(0,120,184,0.08)'}}>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0078B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-bold text-text-primary">Text Message</p>
                      {!isMobile && <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full" style={{background:'rgba(0,120,184,0.08)',color:'#0078B8'}}>Available on mobile</span>}
                    </div>
                    <p className="text-xs text-text-muted">Send a summary via SMS</p>
                  </div>
                </button>

                <button onClick={handlePrint} className="w-full bg-white rounded-2xl px-4 py-3.5 shadow-sm border border-gray-100 flex items-center gap-3 text-left hover:border-pool-dark transition-colors">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:'rgba(0,120,184,0.08)'}}>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0078B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
                  </div>
                  <div>
                    <p className="text-sm font-bold text-text-primary">Print / Save as PDF</p>
                    <p className="text-xs text-text-muted">Bring to your pool store or keep for your records</p>
                  </div>
                </button>

                <button onClick={handleCopy} className="w-full bg-white rounded-2xl px-4 py-3.5 shadow-sm border border-gray-100 flex items-center gap-3 text-left hover:border-pool-dark transition-colors">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background: copied ? 'rgba(29,184,105,0.1)' : 'rgba(0,120,184,0.08)'}}>
                    {copied
                      ? <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#1DB869" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
                      : <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#0078B8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                    }
                  </div>
                  <div>
                    <p className="text-sm font-bold text-text-primary">{copied ? 'Copied!' : 'Copy to Clipboard'}</p>
                    <p className="text-xs text-text-muted">Paste anywhere — notes, another app, etc.</p>
                  </div>
                </button>
              </div>

              {/* Coming soon — user to user */}
              <div className="no-print bg-white rounded-2xl px-4 py-4 shadow-sm border border-gray-100 opacity-60">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:'rgba(0,120,184,0.06)'}}>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#8AAABB" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-bold text-text-primary">Share with a PoolKeep user</p>
                      <span className="text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full" style={{background:'rgba(0,120,184,0.08)',color:'#0078B8'}}>Coming Soon</span>
                    </div>
                    <p className="text-xs text-text-muted mt-0.5">Send reports directly to another PoolKeep account — great for pool services and families managing multiple pools.</p>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>

        {/* Bottom tab bar */}
        <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 px-2 no-print">
          <div className="flex items-center justify-around py-2 max-w-md mx-auto">
            {[
              { id: 'dashboard', label: 'Dashboard', path: '/dashboard', icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg> },
              { id: 'history', label: 'History', path: '/history', icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="12 8 12 12 14 14"/><path d="M3.05 11a9 9 0 1 1 .5 4m-.5 5v-5h5"/></svg> },
              { id: 'log', label: '', path: '/log', icon: null },
              { id: 'share', label: 'Share', path: '/share', icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/></svg> },
              { id: 'pro', label: 'Account', path: '/pro', icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg> },
            ].map(tab => {
              if (tab.id === 'log') return (
                <button key="log" onClick={() => router.push('/log')} className="w-14 h-14 rounded-full bg-pool-dark flex items-center justify-center shadow-lg -mt-5 border-4 border-white">
                  <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
                </button>
              )
              const active = tab.id === 'share'
              return (
                <button key={tab.id} onClick={() => router.push(tab.path)} className="flex flex-col items-center gap-1 px-3 py-1 min-w-0">
                  <span style={{color: active ? '#0078B8' : '#8AAABB'}}>{tab.icon}</span>
                  <span className="text-[10px] font-medium" style={{color: active ? '#0078B8' : '#8AAABB'}}>{tab.label}</span>
                </button>
              )
            })}
          </div>
        </div>
      </div>
    </>
  )
}
